#!/bin/bash
# Convert system lua files into a C file of strings.

fn=mod_lua_system.c

echo create $fn

cat <<EOF >$fn
/*
 * Copyright 2008-2018 Aerospike, Inc.
 *
 * Portions may be licensed to Aerospike, Inc. under one or more contributor
 * license agreements.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
#include <aerospike/as_std.h>

// This system lua code in the lua-core repo have been converted to these strings.
EOF

function ConvertFile {
  name=$1
  echo >> $fn
  echo "const char as_lua_$name[] =" >> $fn

  awk '{
    if ($1 != "" && $1 != "--" && !($1 ~ /^require/)) {
      gsub(/"/,"\\\"",$0);
      printf("\"%s\\n\"\n",$0);
    }
  }' $name.lua >> $fn

  echo ";" >> $fn
  echo >> $fn
  echo "size_t as_lua_"$name"_size = sizeof(as_lua_$name);" >> $fn
}

ConvertFile as
ConvertFile stream_ops
ConvertFile aerospike
